# Generated by Django 3.0.3 on 2020-02-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='stock',
            new_name='asset',
        ),
    ]
