# Generated by Django 3.0.3 on 2020-02-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.DecimalField(
                decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='time_of_last_price',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('holdings', models.ManyToManyField(to='core.Stock')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
