# Generated by Django 3.0.3 on 2020-02-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200226_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_shares', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='asset',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='holdings',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Portfolio'),
        ),
        migrations.AddField(
            model_name='holding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stock'),
        ),
    ]
