# Generated by Django 3.0.3 on 2020-03-02 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200229_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core.Portfolio'),
        ),
    ]
