# Generated by Django 3.0.3 on 2020-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200307_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='high_price',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='low_price',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='open_price',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='time_stamp',
            field=models.DateTimeField(default='1969-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='latest_price_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=255),
        ),
    ]
