# Generated by Django 3.0.3 on 2020-03-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200307_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutePrice',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('open_price', models.DecimalField(blank=True,
                                                   decimal_places=2, max_digits=10, null=True)),
                ('close_price', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(blank=True,
                                                   decimal_places=2, max_digits=10, null=True)),
                ('low_price', models.DecimalField(blank=True,
                                                  decimal_places=2, max_digits=10, null=True)),
                ('volume', models.IntegerField()),
                ('stock', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.Stock')),
            ],
        ),
    ]
