# Generated by Django 3.0.3 on 2020-03-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_minuteprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
