# Generated by Django 3.0.3 on 2020-03-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200309_0204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together={('stock', 'time_stamp')},
        ),
        migrations.AlterUniqueTogether(
            name='minuteprice',
            unique_together={('stock', 'time_stamp')},
        ),
    ]
