# Generated by Django 3.0.3 on 2020-04-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200324_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='limit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_type',
            field=models.CharField(default='Market', max_length=255),
        ),
    ]
