# Generated by Django 3.0.3 on 2020-04-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200408_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price_per_share',
            new_name='price',
        ),
    ]
