# Generated by Django 3.0.3 on 2020-04-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200408_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
