# Generated by Django 3.0.3 on 2020-04-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_holding_average_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
