# Generated by Django 3.0.3 on 2020-04-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_portfoliobalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='latest_price_date',
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
