# Generated by Django 3.0.3 on 2020-04-17 19:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200416_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=core.models.user_image_file_path),
        ),
    ]
